# Generated by Django 4.0.4 on 2022-04-17 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3app', '0002_alter_age_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Age',
        ),
    ]
